services:

    zabbix_postgres:
        container_name: zabbix_postgres
        user: "${DOCKER_POSTGRES_UID}:${DOCKER_POSTGRES_GID}"
        build:
            context: .
            dockerfile: ./docker/postgres/Dockerfile
        ports:
            - "127.0.0.1:5432:5432"
        env_file:
            - .env
        environment:
            PGDATA: /pgdata
        volumes:
            - ./volumes/postgres/pgdata:/pgdata
        restart: always
        cap_drop:
            - ALL
        security_opt:
            - no-new-privileges:true
        networks:
            zabbix_network:
                ipv4_address: 172.20.0.2

    zabbix_server:
        user: "${DOCKER_LINUX_UID}:${DOCKER_LINUX_GID}"
        build:
            context: .
            dockerfile: ./docker/zabbix-server/Dockerfile
        ports:
            - "127.0.0.1:10051:10051"
        env_file:
            - .env
        restart: always
        depends_on:
            - postgres
        cap_drop:
            - ALL
        security_opt:
            - no-new-privileges:true
        networks:
            zabbix_network:
                ipv4_address: 172.20.0.3

networks:
    zabbix_network:
        driver: bridge
        ipam:
            config:
                -   subnet: 172.20.0.0/24